# Generated by Django 3.0.5 on 2020-07-05 09:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_auto_20200705_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 9, 51, 14, 761810, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 9, 51, 14, 763957, tzinfo=utc)),
        ),
    ]
